# Generated by Django 5.2.15 on 2026-06-03 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id_aseguradora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_aseguradora', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aseguradora',
            },
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documentacion',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Licencias',
            fields=[
                ('id_licencias', models.AutoField(primary_key=True, serialize=False)),
                ('numero_licencia', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'licencias',
            },
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id_rutas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ruta', models.CharField(max_length=200)),
                ('lugar_salida', models.CharField(max_length=150)),
                ('lugar_llega', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rutas',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('id_conductores', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=5)),
                ('lugar_recidencia', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_aseguradora', models.ForeignKey(db_column='id_aseguradora', on_delete=django.db.models.deletion.CASCADE, to='api.aseguradora')),
                ('id_documento', models.ForeignKey(db_column='id_documentos', on_delete=django.db.models.deletion.CASCADE, to='api.documentacion')),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('id_licencia', models.ForeignKey(db_column='id_lincecias', on_delete=django.db.models.deletion.CASCADE, to='api.licencias')),
            ],
            options={
                'db_table': 'conductores',
            },
        ),
        migrations.CreateModel(
            name='Pasajeros',
            fields=[
                ('id_pasajeros', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_documento', models.ForeignKey(db_column='id_documentos', on_delete=django.db.models.deletion.CASCADE, to='api.documentacion')),
            ],
            options={
                'db_table': 'pasajeros',
            },
        ),
        migrations.CreateModel(
            name='Estaciones',
            fields=[
                ('id_estaciones', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estacion', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_rutas', models.ForeignKey(db_column='id_rutas', on_delete=django.db.models.deletion.CASCADE, to='api.rutas')),
            ],
            options={
                'db_table': 'estaciones',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('clase_matenimiento', models.CharField(max_length=250)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='api.vehiculo')),
            ],
            options={
                'db_table': 'mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id_viajes', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_viaje', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_ruta', models.ForeignKey(db_column='id_rutas', on_delete=django.db.models.deletion.CASCADE, to='api.rutas')),
            ],
            options={
                'db_table': 'viajes',
            },
        ),
        migrations.CreateModel(
            name='Boletos',
            fields=[
                ('id_boletos', models.AutoField(primary_key=True, serialize=False)),
                ('numero_asiento', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Reservado', 'Reservado'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Reservado', max_length=20)),
                ('id_pasajero', models.ForeignKey(db_column='id_pasajero', on_delete=django.db.models.deletion.CASCADE, to='api.pasajeros')),
                ('id_viaje', models.ForeignKey(db_column='id_viaje', on_delete=django.db.models.deletion.CASCADE, to='api.viajes')),
            ],
            options={
                'db_table': 'boletos',
            },
        ),
    ]
