# Generated by Django 5.2.15 on 2026-06-04 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aseguradora_usuario_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentacion',
            old_name='id_documento',
            new_name='id_documentos',
        ),
    ]
