# Generated by Django 5.2.15 on 2026-06-05 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_id_documento_documentacion_id_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boletos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletos',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
